### PR TITLE
Proper logging

### PR DESCRIPTION
**Pull request by late-goodbye**
Added logging for `list.py`, `test_generator.py` and `list_generator.py` to solve #6 issue.
Implented new class `LoggingManager` which contains basic default configuration for all loggers.
There is only `__init__` method yet, so these default settings may be applied by call the class object instance.
For example, `lm = LoggingManager'

Settings for every logger may be redefined if this action required

The library named logging was used.

### CODE REVIEW

**Comment by vogdb** [comment]
@late-goodbye please resolve conflicts

**Comment by late-goodbye** [comment]
@vogdb done

**Comment by vogdb** [comment]
Do we need this file? Is it a correct format? `fr_Ia_GM_speed15.txt`

**Comment by vogdb** [comment]
I don't know much about python logging but this line looks very wrong to me:
```
  fileConfig(fname='../../logging_config.ini', disable_existing_loggers=False)
```
We must avoid direct file config access. Configuring must be done only once in some `LogManager`. We ought to have something like:
```
fileConfig(some_params_that_override_fileconfig_can_be_here)
```

Again you are rushing without thinking. Please read about logging in python, a proper logging. I don't believe that it is so brutal.

**Comment by vogdb** [comment]
See `log4j` as an example of nice logging interface

**Comment by late-goodbye** [comment]
Impemented the class LoggingManager for the purpose. Now it works without any hardcode.

**Comment by vogdb** [comment]
- I see you are in love with this file `/frequency/frequency_data/fr_Ia_GM_speed15.txt` :cupid:
- Why `main_logger` instead of just `logger`?
- Can we replace
  ```
  self.logger = logging.getLogger('FrequencyList')
  ```
  with
  ```
  self.logger = logging.getLogger(self)
  ```
  or
  ```
  self.logger = logging.getLogger(FrequencyList)
  ```
  ?

**Pull request merged**
